/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.main;

import gui.login.Login;
import java.awt.Color;
import java.awt.Component;
import java.awt.PopupMenu;
import javaswingdev.GradientDropdownMenu;
import javaswingdev.MenuEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        GradientDropdownMenu menu = new GradientDropdownMenu();
        menu.setGradientColor(Color.decode("#2193b0"), Color.decode("#6dd5ed"));
        menu.setBackground(Color.decode("#2980B9"));

        menu.addItem("Trang Chủ", "Trang chủ", "Tài khoản", "Đăng xuất");
        menu.addItem("Thuốc", "Danh sách thuốc", "Quản lý thuốc");
        menu.addItem("Hóa Đơn", "Danh sách hóa đơn", "DS phiếu nhập thuốc", "Ds Phiếu đặt thuốc", "Ds thuốc toa thuốc");
        menu.addItem("Nhân Viên", "Danh sách nhân viên");
        menu.addItem("Khách Hàng", "Danh sách khách hàng");
        menu.addItem("Thống Kê", "Thống kê hóa đơn", "Thống kê thuốc", "Thống kê nhân viên", "Thống kê khách hàng", "Thống kê nhà cung cấp");
        menu.addItem("Nhà Cung Cấp", "Danh sách nhà cung cấp");

        menu.applay(this);
        setLocationRelativeTo(null);

        /**
         * Sự kiện cho từng trang màng hình
         */
        menu.addEvent(new MenuEvent() {
            @Override
            public void selected(int index, int subIndex, boolean menuItem) {
//                throw new UnsupportedOperationException("Not supported yet."); 
                if (menuItem) {
                    String formMenu = menu.getMenuNameAt(index, subIndex).trim();
//                    Trang chủ
                    if (formMenu.equalsIgnoreCase("Đăng xuất")) {
                        Login login = new Login();
                        login.setVisible(true);
                        Main.this.dispose();
                    }
                    if(formMenu.equalsIgnoreCase("Trang chủ")){
                        showForm(new FormHome());
                    }
                    if (formMenu.equalsIgnoreCase("Danh sách nhân viên")) {  
                        showForm(new Form_NhanVien());
                    }
                }
            }
        });

    }
    
    private void showForm(Component com) {
        Form_Home.removeAll();
        Form_Home.add(com);
        Form_Home.repaint();
        Form_Home.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Form_Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        From_Menu_Thua = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Form_Home.setBackground(new java.awt.Color(255, 255, 204));
        Form_Home.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hello menu");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Form_Home.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Form_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1160, 620));

        From_Menu_Thua.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout From_Menu_ThuaLayout = new javax.swing.GroupLayout(From_Menu_Thua);
        From_Menu_Thua.setLayout(From_Menu_ThuaLayout);
        From_Menu_ThuaLayout.setHorizontalGroup(
            From_Menu_ThuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        From_Menu_ThuaLayout.setVerticalGroup(
            From_Menu_ThuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(From_Menu_Thua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Form_Home;
    private javax.swing.JPanel From_Menu_Thua;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
